"""initial database schema

Revision ID: caa3037939ad
Revises: 
Create Date: 2026-06-02 04:57:41.693746

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'caa3037939ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_role',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('role_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_auth_role')),
    sa.UniqueConstraint('role_code', name=op.f('uq_auth_role_role_code'))
    )
    op.create_table('auth_user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE','LOCKED')", name=op.f('ck_auth_user_auth_user_status_allowed')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_auth_user')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_user_email')),
    sa.UniqueConstraint('user_uuid', name=op.f('uq_auth_user_user_uuid'))
    )
    op.create_index('ix_auth_user_status', 'auth_user', ['status'], unique=False)
    op.create_table('dq_rule',
    sa.Column('dq_rule_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=256), nullable=False),
    sa.Column('domain_name', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('rule_expression', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_team', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('INFO','LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_dq_rule_dq_rule_severity_allowed')),
    sa.PrimaryKeyConstraint('dq_rule_id', name=op.f('pk_dq_rule')),
    sa.UniqueConstraint('rule_code', name=op.f('uq_dq_rule_rule_code'))
    )
    op.create_index('ix_dq_rule_domain_severity', 'dq_rule', ['domain_name', 'severity'], unique=False)
    op.create_table('news_source_profile',
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('license_class', sa.String(length=32), nullable=False),
    sa.Column('base_reliability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('base_reliability_score >= 0 AND base_reliability_score <= 100', name=op.f('ck_news_source_profile_news_source_base_reliability_range')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_news_source_profile')),
    sa.UniqueConstraint('source_code', name=op.f('uq_news_source_profile_source_code'))
    )
    op.create_index('ix_news_source_active', 'news_source_profile', ['is_active'], unique=False)
    op.create_table('ops_pipeline_run',
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=128), nullable=False),
    sa.Column('run_mode', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','SUCCESS','FAILED','CANCELLED')", name=op.f('ck_ops_pipeline_run_ops_pipeline_status_allowed')),
    sa.PrimaryKeyConstraint('pipeline_run_id', name=op.f('pk_ops_pipeline_run')),
    sa.UniqueConstraint('run_uuid', name=op.f('uq_ops_pipeline_run_run_uuid'))
    )
    op.create_index('ix_ops_pipeline_name_started', 'ops_pipeline_run', ['pipeline_name', 'started_at'], unique=False)
    op.create_index('ix_ops_pipeline_status', 'ops_pipeline_run', ['status'], unique=False)
    op.create_table('ref_company',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('company_uuid', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('isin_primary', sa.String(length=12), nullable=True),
    sa.Column('sector_code', sa.String(length=32), nullable=True),
    sa.Column('industry_code', sa.String(length=32), nullable=True),
    sa.Column('incorporation_country', sa.String(length=2), nullable=True),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_ref_company')),
    sa.UniqueConstraint('company_uuid', name=op.f('uq_ref_company_company_uuid'))
    )
    op.create_index('ix_ref_company_display_name', 'ref_company', ['display_name'], unique=False)
    op.create_index('ix_ref_company_sector_industry', 'ref_company', ['sector_code', 'industry_code'], unique=False)
    op.create_table('ref_exchange',
    sa.Column('exchange_id', sa.SmallInteger(), nullable=False),
    sa.Column('exchange_code', sa.String(length=16), nullable=False),
    sa.Column('exchange_name', sa.String(length=128), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('exchange_id', name=op.f('pk_ref_exchange')),
    sa.UniqueConstraint('exchange_code', name=op.f('uq_ref_exchange_exchange_code'))
    )
    op.create_index('ix_ref_exchange_active', 'ref_exchange', ['is_active'], unique=False)
    op.create_table('auth_audit_event',
    sa.Column('audit_event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource_code', sa.String(length=128), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.user_id'], name=op.f('fk_auth_audit_event_user_id_auth_user')),
    sa.PrimaryKeyConstraint('audit_event_id', name=op.f('pk_auth_audit_event'))
    )
    op.create_index('gin_auth_audit_payload', 'auth_audit_event', ['event_payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_auth_audit_event_type', 'auth_audit_event', ['event_type'], unique=False)
    op.create_index('ix_auth_audit_user_ts', 'auth_audit_event', ['user_id', 'event_ts'], unique=False)
    op.create_table('auth_permission',
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_code', sa.String(length=128), nullable=False),
    sa.Column('action_code', sa.String(length=64), nullable=False),
    sa.Column('effect', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("effect IN ('ALLOW','DENY')", name=op.f('ck_auth_permission_auth_permission_effect_allowed')),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.role_id'], name=op.f('fk_auth_permission_role_id_auth_role')),
    sa.PrimaryKeyConstraint('permission_id', name=op.f('pk_auth_permission')),
    sa.UniqueConstraint('role_id', 'resource_code', 'action_code', name='ux_auth_permission_role_resource_action')
    )
    op.create_index('ix_auth_permission_resource', 'auth_permission', ['resource_code'], unique=False)
    op.create_table('auth_user_role',
    sa.Column('user_role_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_auth_user_role_auth_user_role_valid_window')),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['auth_user.user_id'], name=op.f('fk_auth_user_role_granted_by_user_id_auth_user')),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.role_id'], name=op.f('fk_auth_user_role_role_id_auth_role')),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.user_id'], name=op.f('fk_auth_user_role_user_id_auth_user')),
    sa.PrimaryKeyConstraint('user_role_id', name=op.f('pk_auth_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', 'valid_from', name='ux_auth_user_role_unique_window')
    )
    op.create_index('ix_auth_user_role_user', 'auth_user_role', ['user_id'], unique=False)
    op.create_table('dq_result',
    sa.Column('dq_result_id', sa.BigInteger(), nullable=False),
    sa.Column('dq_rule_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=True),
    sa.Column('target_table', sa.String(length=128), nullable=False),
    sa.Column('target_record_key', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('measured_value', sa.String(length=256), nullable=True),
    sa.Column('threshold_value', sa.String(length=256), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PASS','FAIL','WARN','SKIPPED')", name=op.f('ck_dq_result_dq_result_status_allowed')),
    sa.ForeignKeyConstraint(['dq_rule_id'], ['dq_rule.dq_rule_id'], name=op.f('fk_dq_result_dq_rule_id_dq_rule')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['ops_pipeline_run.pipeline_run_id'], name=op.f('fk_dq_result_pipeline_run_id_ops_pipeline_run')),
    sa.PrimaryKeyConstraint('dq_result_id', name=op.f('pk_dq_result'))
    )
    op.create_index('ix_dq_result_rule_time', 'dq_result', ['dq_rule_id', 'evaluated_at'], unique=False)
    op.create_index('ix_dq_result_status', 'dq_result', ['status'], unique=False)
    op.create_table('news_article',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('external_article_id', sa.String(length=256), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('article_text_hash', sa.String(length=128), nullable=False),
    sa.Column('article_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_paywalled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('captured_at >= published_at', name=op.f('ck_news_article_news_article_capture_after_publish')),
    sa.ForeignKeyConstraint(['source_id'], ['news_source_profile.source_id'], name=op.f('fk_news_article_source_id_news_source_profile')),
    sa.PrimaryKeyConstraint('article_id', name=op.f('pk_news_article')),
    sa.UniqueConstraint('source_id', 'external_article_id', name='ux_news_article_source_external')
    )
    op.create_index('ix_news_article_hash', 'news_article', ['article_text_hash'], unique=False)
    op.create_index('ix_news_article_published_at', 'news_article', ['published_at'], unique=False)
    op.create_table('ops_data_lineage',
    sa.Column('lineage_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_asset', sa.String(length=256), nullable=False),
    sa.Column('target_asset', sa.String(length=256), nullable=False),
    sa.Column('transform_id', sa.String(length=128), nullable=False),
    sa.Column('record_count_in', sa.BigInteger(), nullable=True),
    sa.Column('record_count_out', sa.BigInteger(), nullable=True),
    sa.Column('lineage_ts', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('record_count_in IS NULL OR record_count_in >= 0', name=op.f('ck_ops_data_lineage_ops_lineage_record_count_in_non_negative')),
    sa.CheckConstraint('record_count_out IS NULL OR record_count_out >= 0', name=op.f('ck_ops_data_lineage_ops_lineage_record_count_out_non_negative')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['ops_pipeline_run.pipeline_run_id'], name=op.f('fk_ops_data_lineage_pipeline_run_id_ops_pipeline_run')),
    sa.PrimaryKeyConstraint('lineage_id', name=op.f('pk_ops_data_lineage'))
    )
    op.create_index('ix_ops_lineage_assets', 'ops_data_lineage', ['source_asset', 'target_asset'], unique=False)
    op.create_index('ix_ops_lineage_run', 'ops_data_lineage', ['pipeline_run_id'], unique=False)
    op.create_table('ops_job_event',
    sa.Column('job_event_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metrics_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("event_type IN ('START','END','WARN','ERROR','RETRY')", name=op.f('ck_ops_job_event_ops_job_event_type_allowed')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['ops_pipeline_run.pipeline_run_id'], name=op.f('fk_ops_job_event_pipeline_run_id_ops_pipeline_run')),
    sa.PrimaryKeyConstraint('job_event_id', name=op.f('pk_ops_job_event'))
    )
    op.create_index('ix_ops_job_event_run', 'ops_job_event', ['pipeline_run_id'], unique=False)
    op.create_index('ix_ops_job_event_type_ts', 'ops_job_event', ['event_type', 'event_ts'], unique=False)
    op.create_table('ops_sla_breach',
    sa.Column('sla_breach_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=True),
    sa.Column('sla_type', sa.String(length=32), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('breach_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','ACKNOWLEDGED','RESOLVED')", name=op.f('ck_ops_sla_breach_ops_sla_status_allowed')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['ops_pipeline_run.pipeline_run_id'], name=op.f('fk_ops_sla_breach_pipeline_run_id_ops_pipeline_run')),
    sa.PrimaryKeyConstraint('sla_breach_id', name=op.f('pk_ops_sla_breach'))
    )
    op.create_index('ix_ops_sla_service_type', 'ops_sla_breach', ['service_name', 'sla_type'], unique=False)
    op.create_index('ix_ops_sla_status', 'ops_sla_breach', ['status'], unique=False)
    op.create_table('ref_calendar',
    sa.Column('calendar_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange_id', sa.SmallInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('session_open_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_close_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holiday_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['ref_exchange.exchange_id'], name=op.f('fk_ref_calendar_exchange_id_ref_exchange')),
    sa.PrimaryKeyConstraint('calendar_id', name=op.f('pk_ref_calendar')),
    sa.UniqueConstraint('exchange_id', 'trade_date', name='ux_ref_calendar_exchange_date')
    )
    op.create_index('ix_ref_calendar_trading_day', 'ref_calendar', ['is_trading_day'], unique=False)
    op.create_table('ref_instrument',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange_id', sa.SmallInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('instrument_type', sa.String(length=32), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("instrument_type IN ('EQUITY','ETF','ADR','PREF')", name=op.f('ck_ref_instrument_instrument_type_allowed')),
    sa.ForeignKeyConstraint(['company_id'], ['ref_company.company_id'], name=op.f('fk_ref_instrument_company_id_ref_company')),
    sa.ForeignKeyConstraint(['exchange_id'], ['ref_exchange.exchange_id'], name=op.f('fk_ref_instrument_exchange_id_ref_exchange')),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_ref_instrument')),
    sa.UniqueConstraint('exchange_id', 'symbol', 'is_active', name='ux_ref_instrument_exchange_symbol_active'),
    sa.UniqueConstraint('instrument_uuid', name=op.f('uq_ref_instrument_instrument_uuid'))
    )
    op.create_index('ix_ref_instrument_company', 'ref_instrument', ['company_id'], unique=False)
    op.create_table('dq_incident',
    sa.Column('dq_incident_id', sa.BigInteger(), nullable=False),
    sa.Column('dq_result_id', sa.BigInteger(), nullable=False),
    sa.Column('incident_status', sa.String(length=16), nullable=False),
    sa.Column('impact_level', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("incident_status IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')", name=op.f('ck_dq_incident_dq_incident_status_allowed')),
    sa.ForeignKeyConstraint(['dq_result_id'], ['dq_result.dq_result_id'], name=op.f('fk_dq_incident_dq_result_id_dq_result')),
    sa.PrimaryKeyConstraint('dq_incident_id', name=op.f('pk_dq_incident'))
    )
    op.create_index('ix_dq_incident_opened', 'dq_incident', ['opened_at'], unique=False)
    op.create_index('ix_dq_incident_status', 'dq_incident', ['incident_status'], unique=False)
    op.create_table('fund_metric_fact',
    sa.Column('metric_fact_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('metric_unit', sa.String(length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('lookback_period', sa.String(length=16), nullable=True),
    sa.Column('calc_version', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_fund_metric_fact_instrument_id_ref_instrument')),
    sa.PrimaryKeyConstraint('metric_fact_id', name=op.f('pk_fund_metric_fact')),
    sa.UniqueConstraint('instrument_id', 'metric_code', 'as_of_date', 'calc_version', name='ux_fund_metric_inst_metric_asof_version')
    )
    op.create_index('ix_fund_metric_metric_code', 'fund_metric_fact', ['metric_code'], unique=False)
    op.create_table('fund_segment_fact',
    sa.Column('segment_fact_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_code', sa.String(length=64), nullable=False),
    sa.Column('segment_name', sa.String(length=128), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('as_reported_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_fund_segment_fact_instrument_id_ref_instrument')),
    sa.PrimaryKeyConstraint('segment_fact_id', name=op.f('pk_fund_segment_fact'))
    )
    op.create_index('ix_fund_segment_inst_segment_period', 'fund_segment_fact', ['instrument_id', 'segment_code', 'fiscal_year', 'fiscal_period'], unique=False)
    op.create_index('ix_fund_segment_metric', 'fund_segment_fact', ['metric_code'], unique=False)
    op.create_table('fund_statement_fact',
    sa.Column('statement_fact_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=8), nullable=False),
    sa.Column('statement_type', sa.String(length=8), nullable=False),
    sa.Column('line_item_code', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('scale_code', sa.String(length=16), nullable=False),
    sa.Column('as_reported_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_from_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("fiscal_period IN ('Q1','Q2','Q3','Q4','FY','H1','H2','TTM')", name=op.f('ck_fund_statement_fact_fund_fiscal_period_allowed')),
    sa.CheckConstraint("statement_type IN ('PL','BS','CF')", name=op.f('ck_fund_statement_fact_fund_statement_type_allowed')),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_fund_statement_fact_instrument_id_ref_instrument')),
    sa.PrimaryKeyConstraint('statement_fact_id', name=op.f('pk_fund_statement_fact'))
    )
    op.create_index('ix_fund_statement_effective_window', 'fund_statement_fact', ['effective_from_ts', 'effective_to_ts'], unique=False)
    op.create_index('ix_fund_statement_inst_period', 'fund_statement_fact', ['instrument_id', 'fiscal_year', 'fiscal_period'], unique=False)
    op.create_index('ix_fund_statement_line_item', 'fund_statement_fact', ['line_item_code'], unique=False)
    op.create_table('market_corporate_action',
    sa.Column('corp_action_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('action_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('action_ratio_num', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('action_ratio_den', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action_type IN ('DIVIDEND','SPLIT','BONUS','RIGHTS','MERGER','DEMERGER')", name=op.f('ck_market_corporate_action_market_corp_action_type_allowed')),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_market_corporate_action_instrument_id_ref_instrument')),
    sa.PrimaryKeyConstraint('corp_action_id', name=op.f('pk_market_corporate_action'))
    )
    op.create_index('ix_market_corp_action_inst_exdate', 'market_corporate_action', ['instrument_id', 'ex_date'], unique=False)
    op.create_index('ix_market_corp_action_type', 'market_corporate_action', ['action_type'], unique=False)
    op.create_table('market_ohlcv_1d',
    sa.Column('ohlcv_1d_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_px', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high_px', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low_px', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close_px', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adj_close_px', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=0), nullable=False),
    sa.Column('turnover', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('high_px >= GREATEST(open_px, close_px)', name=op.f('ck_market_ohlcv_1d_market_ohlcv_1d_high_valid')),
    sa.CheckConstraint('low_px <= LEAST(open_px, close_px)', name=op.f('ck_market_ohlcv_1d_market_ohlcv_1d_low_valid')),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_market_ohlcv_1d_instrument_id_ref_instrument')),
    sa.PrimaryKeyConstraint('ohlcv_1d_id', name=op.f('pk_market_ohlcv_1d')),
    sa.UniqueConstraint('instrument_id', 'trade_date', name='ux_market_ohlcv_1d_inst_date')
    )
    op.create_index('ix_market_ohlcv_1d_date', 'market_ohlcv_1d', ['trade_date'], unique=False)
    op.create_table('market_ohlcv_intraday',
    sa.Column('ohlcv_intraday_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('bar_start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bar_end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bar_interval_sec', sa.Integer(), nullable=False),
    sa.Column('open_px', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high_px', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low_px', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close_px', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=0), nullable=False),
    sa.Column('vwap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('bar_end_ts > bar_start_ts', name=op.f('ck_market_ohlcv_intraday_market_intraday_valid_range')),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_market_ohlcv_intraday_instrument_id_ref_instrument')),
    sa.PrimaryKeyConstraint('ohlcv_intraday_id', name=op.f('pk_market_ohlcv_intraday')),
    sa.UniqueConstraint('instrument_id', 'bar_start_ts', 'bar_interval_sec', name='ux_market_intraday_inst_start_interval')
    )
    op.create_index('ix_market_intraday_time', 'market_ohlcv_intraday', ['bar_start_ts'], unique=False)
    op.create_table('market_orderbook_snapshot',
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('depth_level', sa.SmallInteger(), nullable=False),
    sa.Column('best_bid_px', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('best_bid_qty', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('best_ask_px', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('best_ask_qty', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('book_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('depth_level >= 1', name=op.f('ck_market_orderbook_snapshot_market_orderbook_depth_positive')),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_market_orderbook_snapshot_instrument_id_ref_instrument')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_market_orderbook_snapshot'))
    )
    op.create_index('gin_market_orderbook_payload', 'market_orderbook_snapshot', ['book_payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_market_orderbook_inst_ts', 'market_orderbook_snapshot', ['instrument_id', 'snapshot_ts'], unique=False)
    op.create_table('news_entity_link',
    sa.Column('entity_link_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('mention_type', sa.String(length=32), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 100', name=op.f('ck_news_entity_link_news_entity_relevance_range')),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.article_id'], name=op.f('fk_news_entity_link_article_id_news_article')),
    sa.ForeignKeyConstraint(['company_id'], ['ref_company.company_id'], name=op.f('fk_news_entity_link_company_id_ref_company')),
    sa.PrimaryKeyConstraint('entity_link_id', name=op.f('pk_news_entity_link')),
    sa.UniqueConstraint('article_id', 'company_id', 'mention_type', name='ux_news_entity_unique')
    )
    op.create_index('ix_news_entity_company', 'news_entity_link', ['company_id'], unique=False)
    op.create_table('news_event',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_subtype', sa.String(length=64), nullable=True),
    sa.Column('event_direction', sa.String(length=16), nullable=True),
    sa.Column('event_severity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_direction IS NULL OR event_direction IN ('POSITIVE','NEGATIVE','NEUTRAL')", name=op.f('ck_news_event_news_event_direction_allowed')),
    sa.CheckConstraint('event_confidence >= 0 AND event_confidence <= 100', name=op.f('ck_news_event_news_event_confidence_range')),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.article_id'], name=op.f('fk_news_event_article_id_news_article')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_news_event'))
    )
    op.create_index('gin_news_event_payload', 'news_event', ['event_payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_news_event_article', 'news_event', ['article_id'], unique=False)
    op.create_index('ix_news_event_type', 'news_event', ['event_type'], unique=False)
    op.create_table('news_reliability_score',
    sa.Column('reliability_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('source_reliability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('content_consistency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cross_source_confirmation', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_reliability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('content_consistency >= 0 AND content_consistency <= 100', name=op.f('ck_news_reliability_score_news_rel_content_consistency_range')),
    sa.CheckConstraint('cross_source_confirmation >= 0 AND cross_source_confirmation <= 100', name=op.f('ck_news_reliability_score_news_rel_cross_source_confirmation_range')),
    sa.CheckConstraint('final_reliability_score >= 0 AND final_reliability_score <= 100', name=op.f('ck_news_reliability_score_news_rel_final_score_range')),
    sa.CheckConstraint('source_reliability >= 0 AND source_reliability <= 100', name=op.f('ck_news_reliability_score_news_rel_source_reliability_range')),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.article_id'], name=op.f('fk_news_reliability_score_article_id_news_article')),
    sa.PrimaryKeyConstraint('reliability_id', name=op.f('pk_news_reliability_score')),
    sa.UniqueConstraint('article_id', 'scoring_version', name='ux_news_rel_article_version')
    )
    op.create_index('ix_news_rel_final_score', 'news_reliability_score', ['final_reliability_score'], unique=False)
    op.create_table('ref_symbol_alias',
    sa.Column('alias_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('alias_symbol', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_ref_symbol_alias_instrument_id_ref_instrument')),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_ref_symbol_alias'))
    )
    op.create_index('ix_ref_symbol_alias_inst', 'ref_symbol_alias', ['instrument_id'], unique=False)
    op.create_index('ix_ref_symbol_alias_source_symbol', 'ref_symbol_alias', ['source_system', 'alias_symbol'], unique=False)
    op.create_index('ix_ref_symbol_alias_validity', 'ref_symbol_alias', ['valid_from', 'valid_to'], unique=False)
    op.create_table('val_run',
    sa.Column('val_run_id', sa.BigInteger(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','SUCCESS','FAILED','OVERRIDDEN')", name=op.f('ck_val_run_val_run_status_allowed')),
    sa.ForeignKeyConstraint(['instrument_id'], ['ref_instrument.instrument_id'], name=op.f('fk_val_run_instrument_id_ref_instrument')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['ops_pipeline_run.pipeline_run_id'], name=op.f('fk_val_run_pipeline_run_id_ops_pipeline_run')),
    sa.PrimaryKeyConstraint('val_run_id', name=op.f('pk_val_run')),
    sa.UniqueConstraint('run_uuid', name=op.f('uq_val_run_run_uuid'))
    )
    op.create_index('ix_val_run_inst_asof', 'val_run', ['instrument_id', 'as_of_ts'], unique=False)
    op.create_index('ix_val_run_status', 'val_run', ['status'], unique=False)
    op.create_table('dq_override',
    sa.Column('dq_override_id', sa.BigInteger(), nullable=False),
    sa.Column('dq_incident_id', sa.BigInteger(), nullable=False),
    sa.Column('approved_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('override_expiry_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['auth_user.user_id'], name=op.f('fk_dq_override_approved_by_user_id_auth_user')),
    sa.ForeignKeyConstraint(['dq_incident_id'], ['dq_incident.dq_incident_id'], name=op.f('fk_dq_override_dq_incident_id_dq_incident')),
    sa.PrimaryKeyConstraint('dq_override_id', name=op.f('pk_dq_override'))
    )
    op.create_index('ix_dq_override_expiry', 'dq_override', ['override_expiry_ts'], unique=False)
    op.create_index('ix_dq_override_incident', 'dq_override', ['dq_incident_id'], unique=False)
    op.create_table('fund_restatement_log',
    sa.Column('restatement_id', sa.BigInteger(), nullable=False),
    sa.Column('statement_fact_id', sa.BigInteger(), nullable=False),
    sa.Column('restatement_type', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('new_value', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.CheckConstraint('new_value <> old_value', name=op.f('ck_fund_restatement_log_fund_restatement_value_changed')),
    sa.ForeignKeyConstraint(['statement_fact_id'], ['fund_statement_fact.statement_fact_id'], name=op.f('fk_fund_restatement_log_statement_fact_id_fund_statement_fact')),
    sa.PrimaryKeyConstraint('restatement_id', name=op.f('pk_fund_restatement_log'))
    )
    op.create_index('ix_fund_restatement_detected', 'fund_restatement_log', ['detected_at'], unique=False)
    op.create_index('ix_fund_restatement_fact', 'fund_restatement_log', ['statement_fact_id'], unique=False)
    op.create_table('val_assumption_set',
    sa.Column('assumption_set_id', sa.BigInteger(), nullable=False),
    sa.Column('val_run_id', sa.BigInteger(), nullable=False),
    sa.Column('assumption_key', sa.String(length=128), nullable=False),
    sa.Column('assumption_value_numeric', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('assumption_value_text', sa.Text(), nullable=True),
    sa.Column('assumption_unit', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('assumption_value_numeric IS NOT NULL OR assumption_value_text IS NOT NULL', name=op.f('ck_val_assumption_set_val_assumption_one_value_present')),
    sa.ForeignKeyConstraint(['val_run_id'], ['val_run.val_run_id'], name=op.f('fk_val_assumption_set_val_run_id_val_run')),
    sa.PrimaryKeyConstraint('assumption_set_id', name=op.f('pk_val_assumption_set')),
    sa.UniqueConstraint('val_run_id', 'assumption_key', name='ux_val_assumption_unique')
    )
    op.create_index('ix_val_assumption_source_type', 'val_assumption_set', ['source_type'], unique=False)
    op.create_table('val_attribution',
    sa.Column('attribution_id', sa.BigInteger(), nullable=False),
    sa.Column('val_run_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_type', sa.String(length=64), nullable=False),
    sa.Column('driver_key', sa.String(length=128), nullable=False),
    sa.Column('impact_value_abs', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('impact_value_pct', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('evidence_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("direction IN ('UP','DOWN','NEUTRAL')", name=op.f('ck_val_attribution_val_attr_direction_allowed')),
    sa.ForeignKeyConstraint(['val_run_id'], ['val_run.val_run_id'], name=op.f('fk_val_attribution_val_run_id_val_run')),
    sa.PrimaryKeyConstraint('attribution_id', name=op.f('pk_val_attribution'))
    )
    op.create_index('ix_val_attr_driver', 'val_attribution', ['driver_type', 'driver_key'], unique=False)
    op.create_index('ix_val_attr_run', 'val_attribution', ['val_run_id'], unique=False)
    op.create_table('val_confidence_snapshot',
    sa.Column('confidence_id', sa.BigInteger(), nullable=False),
    sa.Column('val_run_id', sa.BigInteger(), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('management_credibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('industry_stability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('forecast_accuracy_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('news_reliability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('model_agreement_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scenario_dispersion_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('data_quality_score >= 0 AND data_quality_score <= 100', name=op.f('ck_val_confidence_snapshot_val_conf_data_quality_range')),
    sa.CheckConstraint('forecast_accuracy_score >= 0 AND forecast_accuracy_score <= 100', name=op.f('ck_val_confidence_snapshot_val_conf_forecast_accuracy_range')),
    sa.CheckConstraint('industry_stability_score >= 0 AND industry_stability_score <= 100', name=op.f('ck_val_confidence_snapshot_val_conf_industry_stability_range')),
    sa.CheckConstraint('management_credibility_score >= 0 AND management_credibility_score <= 100', name=op.f('ck_val_confidence_snapshot_val_conf_management_credibility_range')),
    sa.CheckConstraint('model_agreement_score >= 0 AND model_agreement_score <= 100', name=op.f('ck_val_confidence_snapshot_val_conf_model_agreement_range')),
    sa.CheckConstraint('news_reliability_score >= 0 AND news_reliability_score <= 100', name=op.f('ck_val_confidence_snapshot_val_conf_news_reliability_range')),
    sa.CheckConstraint('overall_confidence >= 0 AND overall_confidence <= 100', name=op.f('ck_val_confidence_snapshot_val_conf_overall_range')),
    sa.CheckConstraint('scenario_dispersion_score >= 0 AND scenario_dispersion_score <= 100', name=op.f('ck_val_confidence_snapshot_val_conf_scenario_dispersion_range')),
    sa.ForeignKeyConstraint(['val_run_id'], ['val_run.val_run_id'], name=op.f('fk_val_confidence_snapshot_val_run_id_val_run')),
    sa.PrimaryKeyConstraint('confidence_id', name=op.f('pk_val_confidence_snapshot')),
    sa.UniqueConstraint('val_run_id', 'scoring_version', name='ux_val_conf_run_version')
    )
    op.create_index('ix_val_conf_overall', 'val_confidence_snapshot', ['overall_confidence'], unique=False)
    op.create_table('val_model_output',
    sa.Column('model_output_id', sa.BigInteger(), nullable=False),
    sa.Column('val_run_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('equity_value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('enterprise_value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("model_name IN ('DCF','RELATIVE','SOTP','BLENDED','SCENARIO_WEIGHTED')", name=op.f('ck_val_model_output_val_model_name_allowed')),
    sa.ForeignKeyConstraint(['val_run_id'], ['val_run.val_run_id'], name=op.f('fk_val_model_output_val_run_id_val_run')),
    sa.PrimaryKeyConstraint('model_output_id', name=op.f('pk_val_model_output')),
    sa.UniqueConstraint('val_run_id', 'model_name', 'model_version', name='ux_val_model_run_name_version')
    )
    op.create_index('ix_val_model_name', 'val_model_output', ['model_name'], unique=False)
    op.create_table('val_sensitivity',
    sa.Column('sensitivity_id', sa.BigInteger(), nullable=False),
    sa.Column('model_output_id', sa.BigInteger(), nullable=False),
    sa.Column('assumption_key', sa.String(length=128), nullable=False),
    sa.Column('shock_label', sa.String(length=64), nullable=False),
    sa.Column('shock_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('result_target_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_output_id'], ['val_model_output.model_output_id'], name=op.f('fk_val_sensitivity_model_output_id_val_model_output')),
    sa.PrimaryKeyConstraint('sensitivity_id', name=op.f('pk_val_sensitivity')),
    sa.UniqueConstraint('model_output_id', 'assumption_key', 'shock_label', name='ux_val_sens_model_assumption_shock')
    )
    op.create_index('ix_val_sens_assumption_key', 'val_sensitivity', ['assumption_key'], unique=False)
    op.create_index('ix_val_sens_model_output', 'val_sensitivity', ['model_output_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_val_sens_model_output', table_name='val_sensitivity')
    op.drop_index('ix_val_sens_assumption_key', table_name='val_sensitivity')
    op.drop_table('val_sensitivity')
    op.drop_index('ix_val_model_name', table_name='val_model_output')
    op.drop_table('val_model_output')
    op.drop_index('ix_val_conf_overall', table_name='val_confidence_snapshot')
    op.drop_table('val_confidence_snapshot')
    op.drop_index('ix_val_attr_run', table_name='val_attribution')
    op.drop_index('ix_val_attr_driver', table_name='val_attribution')
    op.drop_table('val_attribution')
    op.drop_index('ix_val_assumption_source_type', table_name='val_assumption_set')
    op.drop_table('val_assumption_set')
    op.drop_index('ix_fund_restatement_fact', table_name='fund_restatement_log')
    op.drop_index('ix_fund_restatement_detected', table_name='fund_restatement_log')
    op.drop_table('fund_restatement_log')
    op.drop_index('ix_dq_override_incident', table_name='dq_override')
    op.drop_index('ix_dq_override_expiry', table_name='dq_override')
    op.drop_table('dq_override')
    op.drop_index('ix_val_run_status', table_name='val_run')
    op.drop_index('ix_val_run_inst_asof', table_name='val_run')
    op.drop_table('val_run')
    op.drop_index('ix_ref_symbol_alias_validity', table_name='ref_symbol_alias')
    op.drop_index('ix_ref_symbol_alias_source_symbol', table_name='ref_symbol_alias')
    op.drop_index('ix_ref_symbol_alias_inst', table_name='ref_symbol_alias')
    op.drop_table('ref_symbol_alias')
    op.drop_index('ix_news_rel_final_score', table_name='news_reliability_score')
    op.drop_table('news_reliability_score')
    op.drop_index('ix_news_event_type', table_name='news_event')
    op.drop_index('ix_news_event_article', table_name='news_event')
    op.drop_index('gin_news_event_payload', table_name='news_event', postgresql_using='gin')
    op.drop_table('news_event')
    op.drop_index('ix_news_entity_company', table_name='news_entity_link')
    op.drop_table('news_entity_link')
    op.drop_index('ix_market_orderbook_inst_ts', table_name='market_orderbook_snapshot')
    op.drop_index('gin_market_orderbook_payload', table_name='market_orderbook_snapshot', postgresql_using='gin')
    op.drop_table('market_orderbook_snapshot')
    op.drop_index('ix_market_intraday_time', table_name='market_ohlcv_intraday')
    op.drop_table('market_ohlcv_intraday')
    op.drop_index('ix_market_ohlcv_1d_date', table_name='market_ohlcv_1d')
    op.drop_table('market_ohlcv_1d')
    op.drop_index('ix_market_corp_action_type', table_name='market_corporate_action')
    op.drop_index('ix_market_corp_action_inst_exdate', table_name='market_corporate_action')
    op.drop_table('market_corporate_action')
    op.drop_index('ix_fund_statement_line_item', table_name='fund_statement_fact')
    op.drop_index('ix_fund_statement_inst_period', table_name='fund_statement_fact')
    op.drop_index('ix_fund_statement_effective_window', table_name='fund_statement_fact')
    op.drop_table('fund_statement_fact')
    op.drop_index('ix_fund_segment_metric', table_name='fund_segment_fact')
    op.drop_index('ix_fund_segment_inst_segment_period', table_name='fund_segment_fact')
    op.drop_table('fund_segment_fact')
    op.drop_index('ix_fund_metric_metric_code', table_name='fund_metric_fact')
    op.drop_table('fund_metric_fact')
    op.drop_index('ix_dq_incident_status', table_name='dq_incident')
    op.drop_index('ix_dq_incident_opened', table_name='dq_incident')
    op.drop_table('dq_incident')
    op.drop_index('ix_ref_instrument_company', table_name='ref_instrument')
    op.drop_table('ref_instrument')
    op.drop_index('ix_ref_calendar_trading_day', table_name='ref_calendar')
    op.drop_table('ref_calendar')
    op.drop_index('ix_ops_sla_status', table_name='ops_sla_breach')
    op.drop_index('ix_ops_sla_service_type', table_name='ops_sla_breach')
    op.drop_table('ops_sla_breach')
    op.drop_index('ix_ops_job_event_type_ts', table_name='ops_job_event')
    op.drop_index('ix_ops_job_event_run', table_name='ops_job_event')
    op.drop_table('ops_job_event')
    op.drop_index('ix_ops_lineage_run', table_name='ops_data_lineage')
    op.drop_index('ix_ops_lineage_assets', table_name='ops_data_lineage')
    op.drop_table('ops_data_lineage')
    op.drop_index('ix_news_article_published_at', table_name='news_article')
    op.drop_index('ix_news_article_hash', table_name='news_article')
    op.drop_table('news_article')
    op.drop_index('ix_dq_result_status', table_name='dq_result')
    op.drop_index('ix_dq_result_rule_time', table_name='dq_result')
    op.drop_table('dq_result')
    op.drop_index('ix_auth_user_role_user', table_name='auth_user_role')
    op.drop_table('auth_user_role')
    op.drop_index('ix_auth_permission_resource', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index('ix_auth_audit_user_ts', table_name='auth_audit_event')
    op.drop_index('ix_auth_audit_event_type', table_name='auth_audit_event')
    op.drop_index('gin_auth_audit_payload', table_name='auth_audit_event', postgresql_using='gin')
    op.drop_table('auth_audit_event')
    op.drop_index('ix_ref_exchange_active', table_name='ref_exchange')
    op.drop_table('ref_exchange')
    op.drop_index('ix_ref_company_sector_industry', table_name='ref_company')
    op.drop_index('ix_ref_company_display_name', table_name='ref_company')
    op.drop_table('ref_company')
    op.drop_index('ix_ops_pipeline_status', table_name='ops_pipeline_run')
    op.drop_index('ix_ops_pipeline_name_started', table_name='ops_pipeline_run')
    op.drop_table('ops_pipeline_run')
    op.drop_index('ix_news_source_active', table_name='news_source_profile')
    op.drop_table('news_source_profile')
    op.drop_index('ix_dq_rule_domain_severity', table_name='dq_rule')
    op.drop_table('dq_rule')
    op.drop_index('ix_auth_user_status', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('auth_role')
    # ### end Alembic commands ###
